# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
